# Generated by Django 3.0 on 2021-03-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custName', models.TextField(max_length=45)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IDNo', models.IntegerField()),
                ('AppDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanAmount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interestRate', models.IntegerField()),
            ],
        ),
    ]
