# Generated by Django 3.0 on 2021-03-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20210316_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='LInterest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
