# Generated by Django 3.0 on 2021-03-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_customer_linterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('notify_users', models.BooleanField(default=False)),
                ('notify_users_timestamp', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalInterest', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='LInterest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interestRate',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
