# Generated by Django 3.0 on 2021-03-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_auto_20210316_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.AlterField(
            model_name='customer',
            name='LInterest',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
